apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
nameSuffix: -dev
namespace: gitops-demo-dev
images:
- name: the-website
  newName: ghcr.io/aland-ahmed/the-website
  newTag: v1.0.0-7baac8b
labels:
- includeSelectors: true
  pairs:
    environment: development
replicas:
- count: 3
  name: the-website
patches:
- path: ./patch.yaml
