apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
nameSuffix: -dev
namespace: gitops-demo-dev
images:
- name: the-website
  newTag: v1.0.0
labels:
- includeSelectors: true
  pairs:
    environment: development
replicas:
- count: 3
  name: the-website
