apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: the-website
  namespace: argocd
  #finalizers:
  #- resources-finalizer.argocd.argoproj.io/background
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - env: dev
        namespace: the-website-dev
        revision: master
      - env: staging
        namespace: the-website-staging
        revision: master
      - env: prod
        namespace: the-website-prod
        revision: master
  template:
    metadata:
      name: "the-website-{{ .env }}"
      namespace: argocd
      #finalizers:
      #- resources-finalizer.argocd.argoproj.io/background
      labels:
        app.kubernetes.io/name: the-website
        app.kubernetes.io/instance: "the-website-{{ .env }}"
        environment: "{{ .env }}"
    spec:
      project: the-website-proj
      source:
        repoURL: https://github.com/aland-ahmed/the-website.git
        targetRevision: "{{ .revision }}"
        path: "infrastructure/kubernetes/overlays/{{ .env }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .namespace }}"
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
  templatePatch: |
    {{- if eq .env "prod" }}
    spec:
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
          allowEmpty: false
    {{- else if eq .env "staging" }}
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
          allowEmpty: false
    {{- else }}
    spec:
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
    {{- end }}
