apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: the-website-staging
  namespace: argocd
spec:
  project: the-website-proj 
  source:
    repoURL: https://github.com/aland-ahmed/the-website.git
    targetRevision: master
    path: infrastructure/kubernetes/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: the-website-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
