apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: the-website
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: mastering-gitops
  name: the-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: the-website
      app.kubernetes.io/instance: the-website  # placeholder — overlay must override
  template:
    metadata:
      labels:
        app.kubernetes.io/name: the-website
        app.kubernetes.io/instance: the-website # placeholder — overlay must override
        app.kubernetes.io/component: frontend
        app.kubernetes.io/part-of: mastering-gitops
    spec:
      containers:
        - image: the-website:v1.0.0
          imagePullPolicy: IfNotPresent
          name: the-website
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          #securityContext:
          #  allowPrivilegeEscalation: false
          #  readOnlyRootFilesystem: true
          #  runAsNonRoot: true
          #  runAsUser: 1000
          #  capabilities:
          #    drop: ["ALL"]
      #securityContext:
        #fsGroup: 1000
