apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: the-website
  labels:
    app.kubernetes.io/name: the-website
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: mastering-gitops
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: the-website.local
    http:
      paths:
      - backend:
          service:
            name: the-website
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
