apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gitops-demo

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

labels:
- pairs:
    app.kubernetes.io/name: the-website
  includeTemplates: false
  includeSelectors: true

buildMetadata:
- managedByLabel
#- originAnnotations
#- transformerAnnotations
