apiVersion: v1
kind: Service
metadata:
  name: the-website
  labels:
    app.kubernetes.io/name: the-website
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: mastering-gitops
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: the-website
    app.kubernetes.io/instance: the-website   # placeholder â€” must match pod labels
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  sessionAffinity: ClientIP
