apiVersion: v1
kind: Service
metadata:
  name: the-website
  namespace: gitops-demo
  labels:
    app: the-website
spec:
  type: ClusterIP
  selector:
    app: the-website
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  sessionAffinity: ClientIP
