apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

nameSuffix: -dev
namespace: dev

images:
- name: the-website
  newName: ghcr.io/aland-ahmed/the-website
  newTag: v1.0.0-7baac8b

labels:
- pairs:
    app.kubernetes.io/instance: the-website-dev
    app.kubernetes.io/version: v1.0.0-7baac8b
    environment: dev
  includeSelectors: false # never let kustomize touch selectors
  includeTemplates: true # stamp these onto pod template labels too

replicas:
- count: 1
  name: the-website

patches:
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: dev.the-website.local
  target:
    kind: Ingress
    name: the-website
- patch: |-
    - op: replace
      path: /spec/selector/app.kubernetes.io~1instance
      value: the-website-dev
  target:
    kind: Service
    name: the-website
- patch: |-
    - op: replace
      path: /spec/selector/matchLabels/app.kubernetes.io~1instance
      value: the-website-dev
  target:
    kind: Deployment
    name: the-website
- patch: |-
    - op: replace
      path: /spec/minReplicas
      value: 1
    - op: replace
      path: /spec/maxReplicas
      value: 3
  target:
    kind: HorizontalPodAutoscaler
    name: the-website
