apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-root
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default                # uses the built-in default project
  source:
    repoURL: https://github.com/aland-ahmed/the-website.git
    targetRevision: master
    path: argocd/config
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
